### ISSUE TITLE
Time series plotting problem

### ISSUE THREAD

**Issue by volkanyazici** [faunalia/ps-speed#6]
I edited my CSV file like the shapefile's table struct in the testdata folder. Then, I saved as a shapefile. But time series cannot be plotting. I get a message "No time series values found for the selected point."

My simplified sample data is here: 
https://www.dropbox.com/s/11ig5v967o4oxj8/sample.csv?dl=0

Is there any mistake in the CSV file?

**Comment by ghtmtt** [comment]
Hi. We migrate the plugin repository to gitlab: https://gitlab.com/faunalia/ps-speed/tree/master

could you please open the issue in that repository?
